"""Core renderer for 4_List_renderer.

Takes a result payload (query / brand / results[]) and writes the
list_results_data.js sidecar that Outputs/list_results.html consumes. The
HTML template is stable and is never rewritten here — only the sidecar is.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable

SIDECAR_NAME = "list_results_data.js"

# Per-result keys the template understands. Unknown keys are dropped so a
# noisy upstream source can't bloat the sidecar.
_RESULT_FIELDS = (
    "site_name",
    "url_breadcrumb",
    "favicon",
    "title",
    "title_url",
    "verified",
    "snippet",
    "bold_terms",
    "read_more_url",
)

# Optional identity/ranking fields (spec §4.3): carried through when present so
# later phases (interactions M7, ranking M6) can key off them. The template
# ignores unknown fields, so absent keys are simply omitted to keep the sidecar lean.
_OPTIONAL_FIELDS = ("id", "source_id", "published_at", "topics", "score", "score_breakdown")

_HEADER = (
    "/* list_results_data.js — AUTO-GENERATED by 4_List_renderer.\n"
    " * Do not hand-edit; rerun the renderer (run_4_List_render.bat).\n"
    " * Consumed by the stable Outputs/list_results.html template. */\n"
)


def normalize_result(raw: dict) -> dict:
    """Project one raw result dict down to the template's known fields, plus any
    optional identity/ranking fields that are present."""
    out: dict[str, Any] = {key: raw.get(key) for key in _RESULT_FIELDS}
    out["verified"] = bool(raw.get("verified", False))
    bold = raw.get("bold_terms") or []
    out["bold_terms"] = [str(term) for term in bold]
    for key in _OPTIONAL_FIELDS:
        if raw.get(key) is not None:
            out[key] = raw[key]
    return out


def build_payload(
    query: str | None,
    brand: str | None,
    results: Iterable[dict] | None,
) -> dict:
    """Assemble the window.LIST_DATA payload the template reads."""
    return {
        "query": query or "",
        "brand": brand or "List",
        "results": [normalize_result(r) for r in (results or [])],
    }


def render_sidecar(payload: dict, outputs_dir: Path) -> Path:
    """Write payload to Outputs/list_results_data.js. Returns the path."""
    outputs_dir.mkdir(parents=True, exist_ok=True)
    target = outputs_dir / SIDECAR_NAME
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    target.write_text(
        _HEADER + "window.LIST_DATA = " + body + ";\n", encoding="utf-8"
    )
    return target
